Update callPromisedAppMethod to work with new plugin structure
Countly/countly-server pull request #4372
Opened 2023-07-14 10:44 UTC by John-Weak

[fix] callPromisedAppMethod

2023-07-17 09:57 UTC, kanwarujjaval approved these changes

2023-07-17 11:20 UTC, Cookiezaurs requested changes
Left comment

2023-07-17 11:20 UTC, Cookiezaurs commented on plugins/pluginManager.js
> +                        let ret = methodPromiseCache[method][i].plugin[method](params);
**Can you please do the same as in this.callMethod function.?**

They both use the same methodPromise Cache.
On pushing:
 methodCache[method].push(plugs[i].plugin);

So there would be no change.

2023-07-18 09:00 UTC, kanwarujjaval approved these changes

2023-07-24 10:22 UTC, merged