[SER-857]changes for feedback custom segments
Countly/countly-server pull request #4561
Opened 2023-09-22 09:18 UTC by abhisheksingla02

2023-09-25 05:29 UTC, kanwarujjaval requested changes

2023-09-25 05:29 UTC, kanwarujjaval commented on plugins/star-rating/frontend/public/templates/feedback-popup.html
> +        var custom = { sg: JSON.parse(getParameterByName('segmentation')) };
This needs error handling

2023-09-25 09:23 UTC, John-Weak approved these changes

2023-09-27 09:20 UTC, kanwarujjaval approved these changes

2023-09-27 09:20 UTC, merged