[SER-969] Remove internal sdk methods from heatmap js
Countly/countly-server pull request #4983
Opened 2024-03-14 06:54 UTC by widatama

2024-03-14 09:30 UTC, turtledreams requested changes
also havent seen additional logs except 1 place. it would be best to add some logs for future debugging.

2024-03-14 23:58 UTC, widatama commented
> also havent seen additional logs except 1 place. it would be best to add some logs for future debugging.

I couldn't find any other failure spot like http request that needs logging. Any suggestions?

2024-03-15 05:44 UTC, widatama commented on plugins/views/frontend/public/heatmap.js
> +        if (Countly && Countly.debug && typeof console !== 'undefined') {
Updated

2024-03-15 05:44 UTC, widatama commented on plugins/views/frontend/public/heatmap.js
> -            xhr.setRequestHeader("countly-token", Countly._internals.getToken());
Updated

2024-03-15 07:18 UTC, turtledreams commented
> > also havent seen additional logs except 1 place. it would be best to add some logs for future debugging.
> 
> I couldn't find any other failure spot like http request that needs logging. Any suggestions?

Fair point but I think we shouldn't only look for failure points to add logs. It would be valuable to get the logs indicating the inner workings of functions or the app state. like the initial state, what is being called, and maybe what is returned. There are plenty of operations happening but when I open the console only thing I see is "[INFO] [Countly] [Heatmap] [sendXmlHttpRequest] Sending XML HTTP request". There can be calculations happening which are non breaking but make things not function as normal. We would ask for a client to return these logs in the future and anything we add now can be useful later. What do you think?

2024-03-15 07:21 UTC, turtledreams commented
I checked your test environment and when I select anything other than 'all' I saw sth like this:
![image](https://github.com/Countly/countly-server/assets/62231246/7bc7b08b-f065-4f08-bf7c-f88d04f04589)
why do you think that is? do you think that dropdown is misleading? we can have a call with product maybe to discuss that if you think so.

2024-03-15 09:53 UTC, widatama commented
> I checked your test environment and when I select anything other than 'all' I saw sth like this: ![image](https://private-user-images.githubusercontent.com/62231246/313101203-7bc7b08b-f065-4f08-bf7c-f88d04f04589.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0ODc1NzEsIm5iZiI6MTcxMDQ4NzI3MSwicGF0aCI6Ii82MjIzMTI0Ni8zMTMxMDEyMDMtN2JjN2IwOGItZjA2NS00ZjA4LWJmN2MtZjg4ZDA0ZjA0NTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDA3MjExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MzBkMjQ2NDEzN2I3ZjUxZDA3OTc4Y2Q5OWVhNjg0NmJkNmJlODU1NWVjMzk4NDlmYmI1MjNmY2FjYTQyNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZGSIYgGeagMeGN6xYHLd032v9I18GOrmJmlsYz_36KE) why do you think that is? do you think that dropdown is misleading? we can have a call with product maybe to discuss that if you think so.

There could be a problem with the token. It should've return empty when there's no heatmap data
![Screenshot-20240315164656](https://github.com/Countly/countly-server/assets/1037943/a13243ba-88a4-4802-9c81-52fff12e035c)
Is the token still exists on that page? See if it's in localStorage `cly_token`
![Screenshot-20240315165247](https://github.com/Countly/countly-server/assets/1037943/1a54f01c-48de-488e-ab74-0da4abd21f63)

2024-03-15 10:21 UTC, kanwarujjaval approved these changes

2024-03-20 05:53 UTC, turtledreams approved these changes

2024-03-20 13:13 UTC, ArtursKadikis requested changes
This is missing logs for all functions to see in the flow

2024-03-25 11:47 UTC, ArtursKadikis requested changes
Following changes for the log calls in "getDocHeight", "getDocWidth",  "getViewportHeight":
* they should be debug level
* they should print the returned value

Functions that don't have any params shouldn't print " [].slice.call(arguments)"

Let us wrap the "drawData" calls in a try catch and print the errors

2024-03-25 11:47 UTC, ArtursKadikis commented on plugins/views/frontend/public/heatmap.js
> +            log(logLevelEnums.INFO, "[sendXmlHttpRequest] Sending XML HTTP request");
let us print the params and apiPath here

2024-03-25 11:47 UTC, ArtursKadikis commented on plugins/views/frontend/public/heatmap.js
> +                        log(logLevelEnums.ERROR, "[sendXmlHttpRequest] Failed, trying fallback header");
This logged message doesn't seem to be correctly describing what is happening here.

2024-03-25 11:47 UTC, ArtursKadikis commented on plugins/views/frontend/public/heatmap.js
> +                    log(logLevelEnums.ERROR, "[sendXmlHttpRequest] Failed Server XML HTTP request", this.status);
we should also print the response

2024-03-29 11:24 UTC, widatama commented
Updated

2024-04-01 05:34 UTC, kanwarujjaval approved these changes

2024-04-02 12:38 UTC, ArtursKadikis approved these changes

2024-04-02 12:40 UTC, merged